name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=0.0.0-ci --output .
    - name: Test
      run: dotnet test --configuration Release
    - name: Install Lambda Template
      run: dotnet new --install ./Stackage.Aws.Lambda.DotNetNew.Templates.0.0.0-ci.nupkg
    - name: Use Lambda Template
      run: dotnet new slm --name Lambda.Function
    - name: Build Generated Lambda
      working-directory: ./Lambda.Function
      shell: pwsh
      run: ./build.ps1
