name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=0.0.0-ci --output .
    - name: Test
      run: dotnet test --configuration Release
